# Delete these routes and define your own shop routes here

fiftydeg_sylius_scripts_plugin_static_welcome:
    path: /static-welcome/{name}
    defaults:
        _controller: FiftyDeg\SyliusScriptsPlugin\Controller\GreetingController::staticallyGreetAction
        name: ~

fiftydeg_sylius_scripts_plugin_dynamic_welcome:
    path: /dynamic-welcome/{name}
    defaults:
        _controller: FiftyDeg\SyliusScriptsPlugin\Controller\GreetingController::dynamicallyGreetAction
        name: ~
